// Code generated by sqlc. DO NOT EDIT.

package db_queries

import (
	"database/sql"
	"time"
)

type Belongtoteam struct {
	Staff     string       `json:"staff"`
	Team      string       `json:"team"`
	StartDate time.Time    `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

type Booking struct {
	ID        int32     `json:"id"`
	Booker    string    `json:"booker"`
	Room      string    `json:"room"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

type Room struct {
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	MaxCapacity sql.NullInt32  `json:"max_capacity"`
}

type Team struct {
	ID          sql.NullString `json:"id"`
	Description sql.NullString `json:"description"`
	TeamLead    sql.NullString `json:"team_lead"`
}

type User struct {
	Email     string         `json:"email"`
	Fullname  string         `json:"fullname"`
	Birthdate time.Time      `json:"birthdate"`
	Mentor    sql.NullString `json:"mentor"`
	StartDate sql.NullTime   `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
}

type Userbooking struct {
	ID         int32  `json:"id"`
	TaggedUser string `json:"tagged_user"`
}
